[package]
name = "bloop-core"
version = "0.1.0"
authors = ["Joe Noel <joe.noel@focusrite.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"futures" = "*"
bson = "1.2.0"
futures-channel = "*"
futures-util = "*"
rand = "*"
serde = { version= "*", features = ["derive"] }
serde_derive = "*"
serde_json = "*"
tempfile = "*"
tokio = { version = "*", features = ["full"] }
tokio-tungstenite = "*"
tungstenite = "*"
uuid = { version = "*", features = ["serde", "v4"] }