[package]
name = "bloop-core"
version = "0.1.0"
authors = ["Joe Noel <joe@joenoel.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
approx = "0.5.1"
bson = "2.2.0"
conv = "0.3.3"
cpal = "0.13.5"
fixed = "1.10.0"
futures = "0.3.21"
futures-channel = "0.3.17"
futures-util = "0.3.17"
home = "0.5.3"
hound = "3.4.0"
midir = "0.7.0"
num-traits = "0.2.14"
rand = "0.8.5"
regex = "1.5"
serde = { version= "1.0.136", features = ["derive"] }
serde_bytes = "0.11.5"
serde_derive = "1.0.126"
serde_json = "1.0.79"
tempfile = "3.3.0"
tokio = { version = "1.18.0", features = ["full"] }
tokio-tungstenite = "0.16.0"
tungstenite = "0.16.0"
uuid = { version = "1.0.0", features = ["serde", "v4"] }