[package]
name = "bloop-core"
version = "0.1.0"
authors = ["Joe Noel <joe.noel@focusrite.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "*", features = ["serde", "v4"] }
rand = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"