[package]
name = "bloop-core"
version = "0.1.0"
authors = ["Joe Noel <joe@joenoel.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
approx = "0.5.1"
bson = "2.5.0"
conv = "0.3.3"
cpal = "0.13.5"
fixed = "1.23.0"
futures = "0.3.21"
futures-channel = "0.3.17"
futures-util = "0.3.17"
home = "0.5.4"
hound = "3.5.0"
midir = "0.9.1"
num-traits = "0.2.15"
rand = "0.8.5"
rawdio = "0.5.0"
regex = "1.7"
serde = { version= "1.0.156", features = ["derive"] }
serde_bytes = "0.11.6"
serde_derive = "1.0.126"
serde_json = "1.0.93"
tempfile = "3.3.0"
tokio = { version = "1.25.0", features = ["full"] }
tokio-tungstenite = "0.18.0"
tungstenite = "0.18.0"
uuid = { version = "1.3.0", features = ["serde", "v4"] }

[patch.crates-io]
rawdio = { path = "../rawdio" }