[package]
name = "bloop-core"
version = "0.1.0"
authors = ["Joe Noel <joe@joenoel.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.78"
approx = "0.5.1"
bson = "2.9.0"
conv = "0.3.3"
cpal = "0.15.2"
fixed = "1.25.1"
futures = "0.3.29"
futures-channel = "0.3.30"
futures-util = "0.3.29"
home = "0.5.4"
hound = "3.5.1"
libmdns = "0.8.0"
midir = "0.9.1"
num-traits = "0.2.18"
rand = "0.8.5"
rawdio = { git = "https://github.com/joefocusrite/rawdio", branch = "main" }
regex = "1.10"
serde = { version= "1.0.196", features = ["derive"] }
serde_bytes = "0.11.14"
serde_derive = "1.0.126"
serde_json = "1.0.109"
serialport = "4.2.2" 
tempfile = "3.8.1"
tokio = { version = "1.36.0", features = ["full"] }
tokio-serial = "5.4.4"
tokio-tungstenite = "0.20.1"
uuid = { version = "1.7.0", features = ["serde", "v4"] } 
