name: Editor
on: [push]
jobs:
  build-editor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
        working-directory: editor
      - name: Build all
        run: yarn build
        working-directory: editor
