name: 'Build iOS app'

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

jobs:
  build_with_signing:
    runs-on: macos-latest
    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Extract crate version from Cargo.toml
        run: |
          VERSION=$(grep '^version =' Cargo.toml | awk -F\" '{ print $2 }')
          echo "VERSION_NUMBER=$VERSION" >> $GITHUB_ENV

      - name: Setup SSH access for Match
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MATCH_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Add Rust targets for iOS
        run: |
          rustup target add aarch64-apple-ios
          rustup target add aarch64-apple-ios-sim

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: checkout repository
        uses: actions/checkout@v3

      - name: Generate version file
        working-directory: ios
        run: ./version.sh

      - name: Install protobuf compiler
        run: |
          brew install protobuf
          brew install swift-protobuf
          protoc --version

      - name: Generate API
        run: ./scripts/build-api.sh

      - name: Build core as XCFramework
        run: ./scripts/build-xcframework.sh

      - name: Run Fastlane beta
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ios
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          BUILD_NUMBER: ${{ github.run_number }}
          VERSION_NUMBER: ${{ env.VERSION_NUMBER }}
        run: |
          bundle install
          bundle exec fastlane beta

      - name: Run Fastlane dev
        if: startsWith(github.ref, 'refs/tags/') == false
        working-directory: ios
        env:
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          bundle install
          bundle exec fastlane dev